a=int(input("숫자 1를 입력하세요.:"))
print(a)
print(type(a))
b=int(input("숫자 2를 입력하세요.:"))
print(b)
print(type(b))
c=int(input("숫자 3를입력하세요.:"))
print(c)
print(type(c))
d=int(input("숫자 4를 입력하세요.:"))
print(d)
print(type(d))
e=int(input("숫자 5를 입력하세요.:"))
print(e)
print(type(e))